### ISSUE TITLE
Issue with 0.4.2

### ISSUE THREAD

**Issue by fabaff** [CERN-CERT/WAD#28]
It seems that there is an issue with the 0.4.2 release which was published.

```bash
$ pip3 install wad
Collecting wad
  Downloading https://files.pythonhosted.org/packages/e8/31/e27ce4d2fd36183b3df34b5764ecc671855de01be782a92e2bbfb26d1fc4/wad-0.4.2.tar.gz (109kB)
     |████████████████████████████████| 112kB 1.5MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-hwowozpm/wad/setup.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hwowozpm/wad/
WARNING: You are using pip version 19.1.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

The archive doesn't looks properly created.

**Comment by nikofil** [comment]
Yup, I messed that up. I created a new release now (as I can't overwrite the current one) that should be properly made.
