### ISSUE TITLE
Fail to run properly under Windows

### ISSUE THREAD

**Issue by cjh0613** [CERN-CERT/WAD#34]
win10 pythonx32 3.8.8 wad0.4.6

```
C:\WINDOWS\system32>wad -u 'https://example.com/'
 (b7484665):clues:ERROR Error while reading JSON file, terminating: 'gbk' codec can't decode byte 0xa1 in position 2638: illegal multibyte sequence
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\wad.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\wad\__main__.py", line 91, in main
    Clues.get_clues(options.clues_file)
  File "c:\program files (x86)\python38-32\lib\site-packages\wad\clues.py", line 38, in get_clues
    self.load_clues(filename)
  File "c:\program files (x86)\python38-32\lib\site-packages\wad\clues.py", line 94, in load_clues
    self.apps, self.categories = self.read_clues_from_file(filename)
  File "c:\program files (x86)\python38-32\lib\site-packages\wad\clues.py", line 55, in read_clues_from_file
    clues = json.load(json_data)
  File "c:\program files (x86)\python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 2638: illegal multibyte sequence
```

After I edit `WAD/wad/clues.py` Line 46 :

https://github.com/cjh0613/WAD/commit/2eb201fc3137f94c9205f3ffb3820a08e21ff5f1

```
json_data = open(filename, encoding='utf-8')
```

But:

```
C:\WINDOWS\system32>wad -u 'https://example.com/'
(b7484665):detection:WARNING Error opening 'https://example.com/', terminating: <urlopen error unknown url type: 'https>
{}
```

That may because Python's built-in urllib module does not support HTTPS protocol, but;

```
C:\WINDOWS\system32>wad -u 'http://example.com/'
(a28d461b):detection:WARNING Error opening 'http://example.com/', terminating: <urlopen error unknown url type: 'http>
{}
```

???

**Comment by cjh0613** [comment]
It hasn't been resolved for a long time, close
